// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuf94wKn8Nj3BQrdahZ8reyhe7hweBry4',
    appId: '1:799154691716:web:944ef0bece1cda5c2eecd1',
    messagingSenderId: '799154691716',
    projectId: 'cloneshopee-7dfe1',
    authDomain: 'cloneshopee-7dfe1.firebaseapp.com',
    storageBucket: 'cloneshopee-7dfe1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDshMRMkGDrLUno25Eg4e8KRrWW9fB_nzE',
    appId: '1:799154691716:android:53013b20ab64b4712eecd1',
    messagingSenderId: '799154691716',
    projectId: 'cloneshopee-7dfe1',
    storageBucket: 'cloneshopee-7dfe1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeGjJpKCCis3onTNumxMjAdZqgzzfw5Rs',
    appId: '1:799154691716:ios:61718a810e0eb2862eecd1',
    messagingSenderId: '799154691716',
    projectId: 'cloneshopee-7dfe1',
    storageBucket: 'cloneshopee-7dfe1.firebasestorage.app',
    iosBundleId: 'com.example.shopeeclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeGjJpKCCis3onTNumxMjAdZqgzzfw5Rs',
    appId: '1:799154691716:ios:61718a810e0eb2862eecd1',
    messagingSenderId: '799154691716',
    projectId: 'cloneshopee-7dfe1',
    storageBucket: 'cloneshopee-7dfe1.firebasestorage.app',
    iosBundleId: 'com.example.shopeeclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuf94wKn8Nj3BQrdahZ8reyhe7hweBry4',
    appId: '1:799154691716:web:403173cd5c714a122eecd1',
    messagingSenderId: '799154691716',
    projectId: 'cloneshopee-7dfe1',
    authDomain: 'cloneshopee-7dfe1.firebaseapp.com',
    storageBucket: 'cloneshopee-7dfe1.firebasestorage.app',
  );
}
