// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRJn4A3YTmG9dkZ5QOGskabS9w0vvDuNc',
    appId: '1:406678876257:web:58c62c16db7388f934ba20',
    messagingSenderId: '406678876257',
    projectId: 'crudtutorial-8904a',
    authDomain: 'crudtutorial-8904a.firebaseapp.com',
    storageBucket: 'crudtutorial-8904a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASatqL458RJdsJcqgs0GTHfOMgkEjRhWc',
    appId: '1:406678876257:android:6c34d44566d8009834ba20',
    messagingSenderId: '406678876257',
    projectId: 'crudtutorial-8904a',
    storageBucket: 'crudtutorial-8904a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8iDmoy6Ihtb1YHoW-4x_3UtHydza1N5s',
    appId: '1:406678876257:ios:948106f4fbc2e59a34ba20',
    messagingSenderId: '406678876257',
    projectId: 'crudtutorial-8904a',
    storageBucket: 'crudtutorial-8904a.firebasestorage.app',
    iosBundleId: 'com.example.shopeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRJn4A3YTmG9dkZ5QOGskabS9w0vvDuNc',
    appId: '1:406678876257:web:376aec998fe3b01f34ba20',
    messagingSenderId: '406678876257',
    projectId: 'crudtutorial-8904a',
    authDomain: 'crudtutorial-8904a.firebaseapp.com',
    storageBucket: 'crudtutorial-8904a.firebasestorage.app',
  );
}
